Repository validator-labs/validatorctl, pull requests merged in 2024-11, with the labels that each got.

#235 chore(main): release 0.2.3
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:M

#262 chore: update plugin versions
  pkg/config/versions.go
  tests/integration/validatorctl/testcases/data/validator.yaml
Labels: size:XS, lgtm

#255 chore(main): release 0.2.4
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:S

#265 chore(main): release 0.2.5
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:S

#274 deps: upgrade to latest AWS and Azure plugins
  go.mod
  go.sum
  pkg/config/versions.go
  tests/integration/validatorctl/testcases/data/validator.yaml
Labels: size:S

#273 chore(main): release 0.2.6
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:S
