Repository validator-labs/validatorctl, pull requests merged in 2024-09, with the labels that each got.

#204 fix: handle validation errors, result count mismatch
  pkg/cmd/validator/validator.go
  pkg/components/validator.go
Labels: bug, size:M, lgtm

#177 chore(main): release 0.1.3
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:M

#207 fix: filter vCenter local file privileges properly, skip KUBECONFIG check when updating passwords in direct mode
  go.mod
  go.sum
  pkg/config/versions.go
  pkg/services/validator/validator_service.go
  pkg/services/validator/vmware.go
  tests/integration/_validator/testcases/data/validator.yaml
Labels: bug, size:M, lgtm

#210 chore(main): release 0.1.4
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: bug, autorelease: pending, size:S

#212 fix: add missing Host.Config.Storage privilege & document
  pkg/config/constants.go
  pkg/utils/embed/resources/validator/vsphere-privileges-7.x.yaml
Labels: documentation, size:XS, lgtm

#205 docs: remove subcommand docs from repo
  README.md
  docs/subcommands.md
  pkg/config/versions.go
  pkg/utils/embed/resources/validator/docs.tmpl
  tests/integration/_validator/testcases/data/validator.yaml
Labels: documentation, size:XL, lgtm

#213 chore(main): release 0.2.0
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: bug, autorelease: pending, size:M

#222 refactor: split ConfigureOrCheckCommand into multiple functions
  cmd/validator.go
  pkg/cmd/validator/validator.go
  pkg/config/versions.go
  tests/integration/validatorctl/testcases/data/validator.yaml
Labels: refactoring, size:L, lgtm

#224 feat: support for Azure quota rule
  go.mod
  go.sum
  pkg/config/constants.go
  pkg/services/validator/azure.go
  tests/integration/validatorctl/testcases/data/azureQuotaResourceSets.json
  tests/integration/validatorctl/testcases/data/azureRbacPermissionSets.json
  tests/integration/validatorctl/testcases/test_validator.go
Labels: bug, new-feature, size:L, lgtm

#227 fix: ignore nil errors in validationResponseOk
  pkg/cmd/validator/validator.go
Labels: bug, size:XS, lgtm

#226 chore(main): release 0.2.1
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
  pkg/config/versions.go
  tests/integration/validatorctl/testcases/data/validator.yaml
Labels: refactoring, autorelease: pending, size:S
