Repository validator-labs/validatorctl, pull requests merged in 2024-08, with the labels that each got.

#116 feat: add docs command; refactor to use embeddedfs pkg
  cmd/root.go
  cmd/validator.go
  go.mod
  go.sum
  pkg/cmd/validator/validator.go
  pkg/logging/logger.go
  pkg/services/validator/vmware.go
  pkg/utils/embed/embed.go
  pkg/utils/embed/resources/validator/docs.tmpl
  pkg/utils/kind/kind.go
Labels: refactoring, new-feature, size:L

#117 feat: read CA certs for network rules, add HTTPFileRules, AMIRules
  go.mod
  go.sum
  pkg/components/validator.go
  pkg/services/validator/aws.go
  pkg/services/validator/aws_test.go
  pkg/services/validator/common.go
  pkg/services/validator/network.go
  pkg/services/validator/network_test.go
  pkg/services/validator/vmware_test.go
  tests/integration/_validator/testcases/test_validator.go
Labels: new-feature, size:XL, lgtm

#115 refactor: simplify helm prompts
  go.mod
  go.sum
  hack/validator.tmpl
  pkg/cmd/validator/validator.go
  pkg/components/network.go
  pkg/components/oci.go
  pkg/components/validator.go
  pkg/components/vsphere.go
  pkg/config/constants.go
  pkg/config/versions.go
  pkg/services/validator/aws.go
  pkg/services/validator/aws_test.go
  pkg/services/validator/azure.go
  pkg/services/validator/common.go
  pkg/services/validator/network.go
  pkg/services/validator/network_test.go
  pkg/services/validator/oci.go
  pkg/services/validator/validator_service.go
  pkg/services/validator/vmware.go
  pkg/services/validator/vmware_test.go
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: refactoring, size:XL, lgtm

#121 refactor!: split plugin rule configuration and installation into separate commands
  cmd/root.go
  cmd/validator.go
  cmd/version.go
  hack/validator.tmpl
  pkg/cmd/validator/validator.go
  pkg/components/validator.go
  pkg/config/config.go
  pkg/services/k8s_service.go
  pkg/services/validator/aws.go
  pkg/services/validator/aws_test.go
  pkg/services/validator/azure.go
  pkg/services/validator/network.go
  pkg/services/validator/network_test.go
  pkg/services/validator/oci.go
  pkg/services/validator/validator_service.go
  pkg/services/validator/vmware.go
  pkg/services/validator/vmware_test.go
  pkg/utils/kind/kind.go
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: refactoring, size:XL, lgtm

#126 refactor: remove -s flag
  cmd/validator.go
  pkg/cmd/validator/validator.go
  pkg/config/config.go
  pkg/services/validator/validator_service.go
  tests/integration/_validator/testcases/test_validator.go
Labels: refactoring, size:M, lgtm

#118 chore(main): release 0.1.0
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: documentation, autorelease: pending, size:M

#137 chore: clean up helpers for setting up oci network and vsphere validation rules
  pkg/components/network.go
  pkg/components/oci.go
  pkg/components/validator.go
  pkg/components/vsphere.go
Labels: refactoring, size:L, lgtm

#144 refactor: add rules subcommand & split out apply/check
  cmd/root.go
  cmd/validator.go
  pkg/cmd/validator/validator.go
  pkg/config/config.go
  pkg/config/versions.go
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: refactoring, size:L

#146 docs: update docs to reflect recent api changes
  README.md
  cmd/validator.go
  docs/subcommands.md
Labels: documentation, size:M, lgtm

#141 chore(main): release 0.1.1
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:S, lgtm

#150 feat: set exit code 2 on validation failure; restore debug log file
  cmd/root.go
  cmd/validator.go
  go.mod
  pkg/cmd/validator/validator.go
  pkg/config/constants.go
  pkg/logging/logger.go
  tests/integration/_validator/testcases/test_validator.go
  tests/integration/common/cli_commands.go
Labels: new-feature, size:L, lgtm

#152 feat: read vCenter privileges from local file or editor
  .gitignore
  .vscode/launch.json
  go.mod
  go.sum
  pkg/components/validator.go
  pkg/config/constants.go
  pkg/services/validator/aws.go
  pkg/services/validator/azure.go
  pkg/services/validator/vmware.go
  pkg/utils/embed/resources/validator/vsphere-root-level-privileges-all.yaml
  tests/integration/_validator/testcases/data/awsIAMPolicy.json
  tests/integration/_validator/testcases/data/vCenterPrivileges.txt
  tests/integration/_validator/testcases/test_validator.go
Labels: new-feature, size:XXL, lgtm

#154 refactor: remove explicit TypeMetas; use vapi constants
  go.mod
  go.sum
  pkg/cmd/validator/validator.go
  pkg/services/validator/oci.go
  pkg/utils/kube/kube.go
Labels: refactoring, size:M

#161 feat: support configuring oci validationType on a rule
  go.mod
  go.sum
  hack/validator.tmpl
  pkg/config/versions.go
  pkg/services/validator/oci.go
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: new-feature, size:M, lgtm

#160 feat: add maas plugin
  .gitleaksignore
  .vscode/launch.json
  go.mod
  go.sum
  hack/validator.tmpl
  hack/versions.tmpl
  pkg/cmd/validator/validator.go
  pkg/components/validator.go
  pkg/config/constants.go
  pkg/config/versions.go
  pkg/services/clouds/maas_service.go
  pkg/services/validator/aws.go
  pkg/services/validator/maas.go
  pkg/services/validator/validator_service.go
  pkg/utils/embed/resources/validator/validator-base-values.tmpl
  pkg/utils/embed/resources/validator/validator-plugin-maas-values.tmpl
  pkg/utils/embed/resources/validator/validator-rules-maas.tmpl
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: new-feature, size:XXL, lgtm

#169 fix: correct TUI flow for `validator install -o --apply`
  pkg/cmd/validator/validator.go
  pkg/services/clouds/maas_service.go
  pkg/services/validator/aws.go
  pkg/services/validator/azure.go
  pkg/services/validator/maas.go
  pkg/services/validator/network.go
  pkg/services/validator/oci.go
  pkg/services/validator/validator_service.go
  pkg/services/validator/vmware.go
  tests/integration/_validator/testcases/test_validator.go
Labels: bug, size:L, lgtm

#168 refactor: lazy configuration of oci auth and signature verification secrets
  go.mod
  go.sum
  pkg/cmd/validator/validator.go
  pkg/config/constants.go
  pkg/services/validator/oci.go
  tests/integration/_validator/testcases/test_validator.go
Labels: refactoring, size:L, lgtm

#170 feat: allow specifying Azure cloud to connect to
  go.mod
  go.sum
  pkg/components/validator.go
  pkg/config/constants.go
  pkg/config/versions.go
  pkg/services/validator/azure.go
  pkg/services/validator/validator_service.go
  pkg/utils/embed/resources/validator/validator-plugin-azure-values.tmpl
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: new-feature, size:M, lgtm

#171 feat: allow selecting aws creds from filesystem
  go.mod
  pkg/config/versions.go
  pkg/services/clouds/aws_service.go
  pkg/services/clouds/aws_service_test.go
  pkg/services/validator/aws.go
  tests/integration/_validator/testcases/data/validator.yaml
  tests/unit-test-data/aws_config
  tests/unit-test-data/aws_credentials
Labels: new-feature, size:L, lgtm

#173 feat: support direct oci validation of private registries
  go.mod
  go.sum
  pkg/components/validator.go
  pkg/config/constants.go
  pkg/services/validator/aws.go
  pkg/services/validator/common.go
  pkg/services/validator/oci.go
Labels: new-feature, size:L, lgtm

#176 chore: cleanup comment
  pkg/components/validator.go
Labels: size:XS, lgtm

#179 fix: ensure ErrValidationFailed is returned for maas direct validation failures
  pkg/cmd/validator/validator.go
Labels: bug, size:XS, lgtm

#182 fix: remove duplicate maas base values from template
  pkg/utils/embed/resources/validator/validator-base-values.tmpl
Labels: bug, size:XS, lgtm

#180 fix: only require docker, kind when provisioning kind cluster
  cmd/validator.go
  pkg/cmd/validator/validator.go
  pkg/services/validator/validator_service.go
  pkg/utils/exec/exec.go
Labels: bug, size:S, lgtm

#181 feat: support Azure plugin community gallery image rule
  pkg/components/validator.go
  pkg/services/validator/azure.go
  tests/integration/_validator/testcases/test_validator.go
Labels: refactoring, new-feature, size:L, lgtm

#191 fix: support `validator rules check -f config.yaml` without all plugins defined
  pkg/cmd/validator/validator.go
  pkg/components/validator.go
  pkg/config/versions.go
  tests/integration/_validator/testcases/data/validator.yaml
Labels: bug, size:M, lgtm

#198 feat: inline auth for MAAS
  go.mod
  go.sum
  hack/validator.tmpl
  pkg/cmd/validator/validator.go
  pkg/components/validator.go
  pkg/config/versions.go
  pkg/services/clouds/maas_service.go
  pkg/services/validator/aws.go
  pkg/services/validator/azure.go
  pkg/services/validator/maas.go
  pkg/services/validator/network.go
  pkg/services/validator/oci.go
  pkg/services/validator/rule_names.go
  pkg/services/validator/vmware.go
  pkg/utils/embed/resources/validator/validator-base-values.tmpl
  pkg/utils/embed/resources/validator/validator-plugin-maas-values.tmpl
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: refactoring, size:L, lgtm
