Repository validator-labs/validatorctl, pull requests merged in 2024-07, with the labels that each got.

#66 chore(main): release 0.0.4
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:S

#76 chore: omit EDITOR logs by default
  go.mod
  go.sum
Labels: size:XS, lgtm

#83 feat: add support for private custom image registries
  hack/validator.tmpl
  pkg/components/environment.go
  pkg/components/validator.go
  pkg/config/versions.go
  pkg/services/env_service.go
  pkg/services/validator/aws_test.go
  pkg/services/validator/common.go
  pkg/services/validator/network_test.go
  pkg/services/validator/validator_service.go
  pkg/services/validator/vmware_test.go
  pkg/utils/embed/embed.go
  pkg/utils/kind/kind.go
  pkg/utils/kind/kind_test.go
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
  tests/unit-test-data/kindconfig-airgapped.yaml
  tests/unit-test-data/kindconfig-custom-registry.yaml
Labels: new-feature, size:XL, lgtm

#96 fix: ensure passwords in helm templates are quoted
  go.mod
  go.sum
  pkg/components/network.go
  pkg/components/oci.go
  pkg/components/validator.go
  pkg/components/vsphere.go
  pkg/config/versions.go
  pkg/utils/embed/resources/validator/validator-base-values.tmpl
  tests/integration/_validator/testcases/data/validator.yaml
Labels: bug, size:S, lgtm

#78 chore(main): release 0.0.5
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: autorelease: pending, size:M, lgtm

#97 feat: Azure plugin - remove Palette presets, reading permission set files
  pkg/config/constants.go
  pkg/services/validator/azure.go
  tests/integration/_validator/testcases/data/azurePermissionSets.json
  tests/integration/_validator/testcases/test_validator.go
Labels: enhancement, size:XL, lgtm

#106 chore: bump validator and plugin versions
  go.mod
  go.sum
  pkg/config/versions.go
  pkg/services/validator/network.go
  tests/integration/_validator/testcases/data/validator.yaml
  tests/integration/_validator/testcases/test_validator.go
Labels: size:M, lgtm

#103 chore(main): release 0.0.6
  .release-please-manifest.json
  CHANGELOG.md
  Makefile
Labels: new-feature, autorelease: pending, size:S, lgtm
